### ISSUE TITLE
Incorrect license modification 

### ISSUE THREAD

**Issue by VegaDeftwing** [chrisamirani/knowtes#5]
I see https://github.com/chrisamirani/knowtes/blob/main/src/client/LICENSE that you've used https://github.com/udecode/plate, you can't just add a name to the license file. You're not a copyright holder, presumably.

**Comment by chrisamirani** [comment]
Appreciate you being thorough. Should that license be modified you mean? That left over from the template they offer here https://github.com/udecode/plate/tree/main/templates/plate-playground-template

**Comment by VegaDeftwing** [comment]
Ahh, looks like Plate has two difference MIT license files. You may want to open an issue with them to verify if the file should include `shadcn` or not, since they have two, conflicting licensees.

**Comment by chrisamirani** [comment]
@VegaDeftwing right I see that now. I made a https://github.com/udecode/plate/discussions/3770 as they didn't have an issue category for that. Thanks again

**Comment by chrisamirani** [comment]
@VegaDeftwing  the maintainer replied. Probably need to keep that there for now as i believe part of that code base does use shadcn code.
